fix: fine tune header menu
cmu-delphi/delphi-blog pull request #12
Opened 2020-08-12 16:25 UTC by sgratzl

closes https://github.com/cmu-delphi/www-covidcast/issues/348

![image](https://user-images.githubusercontent.com/4129778/90041130-25dd0380-dcc9-11ea-86fc-cd8f1d6ac436.png)

2020-08-13 13:42 UTC, capnrefsmmat requested changes
Looks good except for one tweak

2020-08-13 13:42 UTC, capnrefsmmat commented on config.toml
> +    name = "Github"
GitHub brands itself GitHub; I think we should actually change the other site to match this, rather than changing the blog to be wrong

2020-08-13 14:10 UTC, sgratzl commented
reverted

2020-08-18 15:09 UTC, capnrefsmmat approved these changes

2020-08-18 15:09 UTC, merged